/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

import COMUNICACAO.Comestoque;
import COMUNICACAO.Comproduto;
import UTIL.ManipularImagem;
import VARIAVEIS.Estoque;
import VARIAVEIS.Produto;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Aluno
 */
public class CadastroProduto1 extends javax.swing.JFrame {
 BufferedImage imagem;
TelaInicial tela;

    public TelaInicial getTela() {
        return tela;
    }

    public void setTela(TelaInicial tela) {
        this.tela = tela;
    }

 
    /**
     * Creates new form CadastroProduto1
     */
    public CadastroProduto1() {
        initComponents();
        v1.setEditable(false);
           DefaultTableModel modelo = (DefaultTableModel) jTable1p.getModel();
       jTable1p.setRowSorter(new TableRowSorter(modelo));

     try {
         readJTable();  //chama esse método assim quando for carregado
     } catch (SQLException ex) {
         Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
     }
//        Produto p = new Produto();
//     try {
//         Comproduto comp = new Comproduto();
//         p=comp.apenasimage(24);
//         ManipularImagem.exibiImagemLabel(p.getImagem(),labelf);
//     } catch (SQLException ex) {
//         Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
//     }
        
    }
    public void escreve(String oi){
        v1.setText(oi);
        
    }
   public void recebecat(String a ,String b , String c1 ,int d1,int e,double i,int v1){
       n.setText("");  
      v.setText("");  
      m.setText("");  
      d.setText("");  
      c.setText("");  
      q1.setText(""); 
   }
       public void readJTableForDesc(String desc) throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1p.getModel();
        modelo.setNumRows(0);
       Comproduto pdao = new Comproduto();

        for (Produto p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
               p.getId(),
                p.getNome(),
                p.getDescricao(),
                p.getMarca(),
                p.getCodigo_produto(),
                p.getQtdminima(),
                p.getCatproduto_idcatproduto(),
                p.getValor()
            });

        }

    }
 
    public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1p.getModel();
        modelo.setNumRows(0); //para tirar todas para nao dá o problema da duplicação
        Comproduto prod = new Comproduto();

        for (Produto p : prod.getLista ()) {  //ele vai pegar o que tiver dentro do array list e colocar
            //dentro do objeto do produto p

            modelo.addRow(new Object[]{    //criamos um vetor que vai pegar o que já tem
                p.getId(),
                p.getNome(),
                p.getDescricao(),
                p.getMarca(),
                p.getCodigo_produto(),
                p.getQtdminima(),
                p.getCatproduto_idcatproduto(),
                p.getValor()
            });
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        q1 = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1p = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        v = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtBuscaDesc = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel2.setLayout(null);

        labelf.setBackground(new java.awt.Color(204, 204, 204));
        labelf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.add(labelf);
        labelf.setBounds(520, 10, 221, 200);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Quantidade Mínima :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 340, 180, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nome :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(16, 199, 180, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Descrição :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(16, 249, 180, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Marca :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 300, 180, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Categoria do Produto :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 480, 196, 30);
        jPanel2.add(n);
        n.setBounds(200, 201, 167, 30);
        jPanel2.add(d);
        d.setBounds(200, 251, 167, 30);
        jPanel2.add(m);
        m.setBounds(200, 300, 167, 30);
        jPanel2.add(q1);
        q1.setBounds(200, 340, 167, 30);
        jPanel2.add(c);
        c.setBounds(200, 390, 167, 30);

        jButton1.setText("Selecionar uma foto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(758, 43, 150, 40);

        jTable1p.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nome", "descrição", "marca", "código do produto", "qtd miníma", "Categoria", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1pMouseClicked(evt);
            }
        });
        jTable1p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1pKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1p);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(410, 220, 953, 230);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Código do Produto :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 390, 180, 30);

        jButton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/y1.png"))); // NOI18N
        jButton5.setText("enviar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(29, 554, 150, 60);

        jButton6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/y2.png"))); // NOI18N
        jButton6.setText("apagar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(193, 554, 150, 60);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/y3.png"))); // NOI18N
        jButton7.setText("Alterar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(750, 490, 144, 57);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/y2.png"))); // NOI18N
        jButton8.setText("Excluir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(950, 490, 150, 60);
        jPanel2.add(v);
        v.setBounds(200, 440, 167, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Valor :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 440, 180, 30);

        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });
        v1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                v1KeyPressed(evt);
            }
        });
        jPanel2.add(v1);
        v1.setBounds(220, 480, 167, 32);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/abrir.png"))); // NOI18N
        jButton2.setText("Abrir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(400, 460, 107, 57);
        jPanel2.add(txtBuscaDesc);
        txtBuscaDesc.setBounds(998, 148, 220, 40);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(1224, 150, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/cad.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1480, 670);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1480, 650);

        jMenu1.setText("Voltar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1489, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Escolher foto do Produto");//o titulo ´lá em cima
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY); 
        FileNameExtensionFilter filter = new  FileNameExtensionFilter("Imagem","jpg","png");
        fc.setFileFilter(filter); 
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
               imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(),270,300);

                labelf.setIcon(new ImageIcon(imagem));

            } catch (Exception ex) {
                // System.out.println(ex.printStackTrace().toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           
        try {
         if(n.getText()==null || v.getText().trim().equals("") ||  m.getText()==null || d.getText().trim().equals("") ||  c.getText()==null || q1.getText().trim().equals("") || imagem==null){
             JOptionPane.showMessageDialog(null,"Preencha os espaços vazios !!");
         }else{      
              Comproduto ver = new Comproduto();
             if (ver.verificaproduto(c.getText())) {
             JOptionPane.showMessageDialog(null,"Este produto já foi cadastrado!!");
             }else{
                 
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente adicionar este produto ?");
//            JOptionPane.showMessageDialog(null,c.getText())
             if (resposta == JOptionPane.YES_OPTION) {
             Produto p = new Produto();
             p.setNome(n.getText());
             p.setValor(Double.parseDouble(v.getText()));
             p.setMarca(m.getText());
             p.setDescricao(d.getText());
             p.setCodigo_produto(c.getText());
             p.setQtdminima(Integer.parseInt(q1.getText()));
             p.setCatproduto_idcatproduto(Integer.valueOf(v1.getText()));
             p.setImagem(ManipularImagem.getImgBytes(imagem));
             
             try {
                 Comproduto cp= new  Comproduto();
                 cp.adiciona(p);
//                 agora eu pego o ultimo registro que foi adicionado e seto o id dele na tabela estoque e fica legal
                 for (Produto soid : cp.soid(p.getCodigo_produto())) { 
                 Comestoque comestoque = new Comestoque();
                 Estoque estoque = new Estoque();
                 estoque.setQtd(0);
                 estoque.setIdproduto(soid.getId());  //pega o id do ultimo que foi cadastrado
                  comestoque.adiciona(estoque);
                 }
//                   fim de agora eu pego o ultimo registro que foi adicionado e seto o id dele na tabela estoque e fica legal
             } catch (SQLException ex) {
                 Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
             }
             }
             }//fim do else para saber se o produto já está cadastrado
         }
         readJTable();
     } catch (SQLException ex) {
         Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      n.setText("");  
      v.setText("");  
      m.setText("");  
      d.setText("");  
      c.setText("");  
      q1.setText("");  
      v1.setText("");  
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
             if (jTable1p.getSelectedRow() != -1) {
                    int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente apagar este produto ?");
                 if (resposta == JOptionPane.YES_OPTION) {   //if para confirmacao
                     
                 
            Produto p = new Produto();
            p.setId((int) jTable1p.getValueAt(jTable1p.getSelectedRow(), 0));  //botando para dentro do array o valor do id
            Comproduto dao;
                 try {
                     dao = new Comproduto();
                     dao.remove(p);
                 } catch (SQLException ex) {
                     Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
                 }

       n.setText("");  
      v.setText("");  
      m.setText("");  
      d.setText("");  
      c.setText("");  
      q1.setText("");  
                 try {
                     readJTable();  //para ler novamente para atualizar
                 } catch (SQLException ex) {
                     Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
                 }

        }} else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1pKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1pKeyReleased
    
    }//GEN-LAST:event_jTable1pKeyReleased

    private void jTable1pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1pMouseClicked
       if (jTable1p.getSelectedRow() != -1) {   
           
           
            n.setText(jTable1p.getValueAt(jTable1p.getSelectedRow(), 1).toString());
            d.setText(jTable1p.getValueAt(jTable1p.getSelectedRow(), 2).toString());
            m.setText(jTable1p.getValueAt(jTable1p.getSelectedRow(), 3).toString());
            c.setText(jTable1p.getValueAt(jTable1p.getSelectedRow(), 4).toString());
            q1.setText(jTable1p.getValueAt(jTable1p.getSelectedRow(), 5).toString());
            v.setText(jTable1p.getValueAt(jTable1p.getSelectedRow(), 7).toString());
            v1.setText(jTable1p.getValueAt(jTable1p.getSelectedRow(), 6).toString());

        }
    }//GEN-LAST:event_jTable1pMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar este produto ?");
        if (resposta == JOptionPane.YES_OPTION) {
        Produto p = new Produto();
            Comproduto dao;
             p.setNome(n.getText());
             p.setValor(Double.parseDouble(v.getText()));
             p.setMarca(m.getText());
             p.setDescricao(d.getText());
             p.setCodigo_produto(c.getText());
             p.setQtdminima(Integer.parseInt(q1.getText()));
             p.setCatproduto_idcatproduto(Integer.parseInt(v1.getText()));
            p.setId((int) jTable1p.getValueAt(jTable1p.getSelectedRow(), 0));  //pegamos o id da linha selecionada
     try {
         dao = new Comproduto();
         dao.altera(p);
          readJTable();
     } catch (SQLException ex) {
         Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
     }
      n.setText("");  
      v.setText("");  
      m.setText("");  
      d.setText("");  
      c.setText("");  
      q1.setText("");  
       
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        CadastroProduto1 cad = this;
        SelecionaCatpro sel = new SelecionaCatpro(cad);
        sel.setVisible(true);
        sel.setRp(cad);
//               sel.setRp(cad);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try {
         // TODO add your handling code here:

         readJTableForDesc(txtBuscaDesc.getText());
     } catch (SQLException ex) {
         Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
     }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
           if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
         if(n.getText()==null || v.getText().trim().equals("") ||  m.getText()==null || d.getText().trim().equals("") ||  c.getText()==null || q1.getText().trim().equals("") || imagem==null) {
             JOptionPane.showMessageDialog(null,"Preencha os espaços vazios !!");
         }else{      
              Comproduto ver = new Comproduto();
             if (ver.verificaproduto(c.getText())) {
             JOptionPane.showMessageDialog(null,"Este produto já foi cadastrado!!");
             }else{
                 
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente adicionar este produto ?");
             if (resposta == JOptionPane.YES_OPTION) {
             Produto p = new Produto();
             p.setNome(n.getText());
             p.setValor(Double.parseDouble(v.getText()));
             p.setMarca(m.getText());
             p.setDescricao(d.getText());
             p.setCodigo_produto(c.getText());
             p.setQtdminima(Integer.parseInt(q1.getText()));
             p.setCatproduto_idcatproduto(5);
             p.setImagem(ManipularImagem.getImgBytes(imagem));
             
             try {
                 Comproduto cp= new  Comproduto();
                 cp.adiciona(p);
             } catch (SQLException ex) {
                 Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
             }
             }
             }//fim do else para saber se o produto já está cadastrado
         }
         readJTable();
     } catch (SQLException ex) {
         Logger.getLogger(CadastroProduto1.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void v1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_v1KeyPressed
      JOptionPane.showMessageDialog(null,"oi!");
    }//GEN-LAST:event_v1KeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
    this.setVisible(false);
    dispose();
    getTela().setVisible(true);      
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1p;
    private javax.swing.JLabel labelf;
    private javax.swing.JTextField m;
    private javax.swing.JTextField n;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField txtBuscaDesc;
    private javax.swing.JTextField v;
    private javax.swing.JTextField v1;
    // End of variables declaration//GEN-END:variables
}
