/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

import CONEXAO.conexao;
import com.mysql.jdbc.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author guilhermefranci
 */
public class Relatorios extends javax.swing.JFrame {
     private Connection co;

    /**
     * Creates new form Relatorios
     */
    public Relatorios() throws SQLException {
        initComponents();
          this.co = conexao.getconexao();
        
    }
    
    TelaInicial volta;

    public TelaInicial getVolta() {
        return volta;
    }

    public void setVolta(TelaInicial volta) {
        this.volta = volta;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lala = new javax.swing.JProgressBar();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel3.setText("Gerenciamente de Relatórios");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 40, 450, 50);
        getContentPane().add(lala);
        lala.setBounds(910, 530, 380, 40);

        jButton7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/botoes/icons8-impressão-80.png"))); // NOI18N
        jButton7.setText("Imprimir Relatório de Administrador");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(140, 430, 400, 89);

        jButton6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/botoes/icons8-impressão-80.png"))); // NOI18N
        jButton6.setText("Imprimir Relatório de Funcionário");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(140, 310, 400, 89);

        jButton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/botoes/icons8-impressão-80.png"))); // NOI18N
        jButton5.setText("Imprimir Relatório de Caixa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(920, 330, 400, 89);

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/botoes/icons8-impressão-80.png"))); // NOI18N
        jButton3.setText("Imprimir Relatório de Fornecedores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 180, 400, 89);

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/botoes/icons8-impressão-80.png"))); // NOI18N
        jButton2.setText("Imprimir Relatório de Produtos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(920, 210, 400, 89);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/carlr.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1480, 670);

        jMenu1.setText("Voltar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1489, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
        
      new Thread(){
             
              public void run(){
                  
                  for (int i=0;i<101;i++){
                      lala.setValue(i);
                   try{
                       Thread.sleep(20);
                   }catch(Exception ex){
                       ex.getMessage();
                   }
                  }
            String src = "report2.jasper";
        
        JasperPrint jaspertPrint = null;
        
        try {
            
            jaspertPrint = JasperFillManager.fillReport(src, null, co);
            
        } catch (JRException ex) {
            System.out.println("Error: "+ex);
        }
        
        JasperViewer view = new JasperViewer(jaspertPrint,false);
        
        view.setVisible(true);
              }
              /////////
              
              
              ////
               
         }.start();;
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new Thread(){
             
              public void run(){
                  
                  for (int i=0;i<101;i++){
                      lala.setValue(i);
                   try{
                       Thread.sleep(20);
                   }catch(Exception ex){
                       ex.getMessage();
                   }
                  }
                     String src = "RelatorioFornecedor.jasper";
        
        JasperPrint jaspertPrint = null;
        
        try {
            
            jaspertPrint = JasperFillManager.fillReport(src, null, co);
            
        } catch (JRException ex) {
            System.out.println("Error: "+ex);
        }
        
        JasperViewer view = new JasperViewer(jaspertPrint,false);
        
        view.setVisible(true);
              }
              /////////
              
              
              ////
               
         }.start();
      
        
               
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         
        
        new Thread(){
             
              public void run(){
                  
                  for (int i=0;i<101;i++){
                      lala.setValue(i);
                   try{
                       Thread.sleep(20);
                   }catch(Exception ex){
                       ex.getMessage();
                   }
                  }
                     String src = "RelatorioCaixa.jasper";
        
        JasperPrint jaspertPrint = null;
        
        try {
            
            jaspertPrint = JasperFillManager.fillReport(src, null, co);
            
        } catch (JRException ex) {
            System.out.println("Error: "+ex);
        }
        
        JasperViewer view = new JasperViewer(jaspertPrint,false);
        
        view.setVisible(true);
              }
              /////////
              
              
              ////
               
         }.start();
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        new Thread(){
             
              public void run(){
                  
                  for (int i=0;i<101;i++){
                      lala.setValue(i);
                   try{
                       Thread.sleep(20);
                   }catch(Exception ex){
                       ex.getMessage();
                   }
                  }
         String src = "RelatorioFuncionario.jasper";
        
        JasperPrint jaspertPrint = null;
        
        try {
            
            jaspertPrint = JasperFillManager.fillReport(src, null, co);
            
        } catch (JRException ex) {
            System.out.println("Error: "+ex);
        }
        
        JasperViewer view = new JasperViewer(jaspertPrint,false);
        
        view.setVisible(true);
              }
              /////////
              
              
              ////
               
         }.start();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
       new Thread(){
             
              public void run(){
                  
                  for (int i=0;i<101;i++){
                      lala.setValue(i);
                   try{
                       Thread.sleep(20);
                   }catch(Exception ex){
                       ex.getMessage();
                   }
                  }
  String src = "RelatorioAdmin.jasper";
        
        JasperPrint jaspertPrint = null;
        
        try {
            
            jaspertPrint = JasperFillManager.fillReport(src, null, co);
            
        } catch (JRException ex) {
            System.out.println("Error: "+ex);
        }
        
        JasperViewer view = new JasperViewer(jaspertPrint,false);
        
        view.setVisible(true);
              }
              /////////
              
              
              ////
               
         }.start();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       this.setVisible(false);
        dispose();
      getVolta().setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Relatorios().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Relatorios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar lala;
    // End of variables declaration//GEN-END:variables
}
