/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

import COMUNICACAO.Comcaixa;
import VARIAVEIS.Caixa;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author guilhermefranci
 */
public class TelaCadCaixa extends javax.swing.JFrame {
TelaInicial tela;

    public TelaInicial getTela() {
        return tela;
    }

    public void setTela(TelaInicial tela) {
        this.tela = tela;
    }

    /**
     * Creates new form TelaCadCaixa
     */
    public TelaCadCaixa() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
       tabela.setRowSorter(new TableRowSorter(modelo));
       f.setEditable(false);
        try {
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void escreve( String par){
        f.setText(par);
    }
       public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0); //para tirar todas para nao dá o problema da duplicação
           Comcaixa prod = new Comcaixa();

        for (Caixa p : prod.getLista ()) {  //ele vai pegar o que tiver dentro do array list e colocar
            //dentro do objeto do produto p
           String ntexto;
           if ( p.getSituacao()) {
                ntexto="aberto";
           }else{
                ntexto="fechado";
               
           }
            modelo.addRow(new Object[]{    //criamos um vetor que vai pegar o que já tem
                p.getId(),
                p.getNomefunc(),
                p.getDinheiro(),
                ntexto
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        q = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/y3.png"))); // NOI18N
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 580, 140, 60);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/y2.png"))); // NOI18N
        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(800, 580, 140, 60);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "funcionário", "qtd_dinheiro", "situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 410, 1440, 150);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/abrir.png"))); // NOI18N
        jButton6.setText("Abrir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(780, 180, 110, 57);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/y1.png"))); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 290, 115, 57);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/y2.png"))); // NOI18N
        jButton4.setText("Apagar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(420, 290, 119, 57);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Funcionário :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 190, 300, 40);
        getContentPane().add(f);
        f.setBounds(420, 190, 330, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade inicial de dinheiro :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 100, 300, 40);
        getContentPane().add(q);
        q.setBounds(420, 100, 330, 40);

        jLabel2.setBackground(new java.awt.Color(255, 51, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("CADASTRO DE CAIXA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(700, 10, 300, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/cad.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1480, 690);

        jMenu1.setText("Voltar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1489, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if(q.getText()==null || f.getText().trim().equals("") ){
                JOptionPane.showMessageDialog(null,"Preencha os espaços vazios !!");
            }else{
                Comcaixa ver = new Comcaixa();
                if (!ver.verificacaixa(Integer.valueOf(f.getText()))) {
                    
                    int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente cadastrar este caixa?");
                    if (resposta == JOptionPane.YES_OPTION) {
                        Caixa p = new Caixa ();
                        p.setDinheiro(Double.parseDouble((q.getText())));
                        p.setIdfuncionario(Integer.parseInt((f.getText())));
                        p.setSituacao(false);
                      

                        try {
                            Comcaixa cp = new Comcaixa();
                            cp.adiciona(p);
                        } catch (SQLException ex) {
                            Logger.getLogger(TelaCadCaixa.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }//fim do else para saber se o produto já está cadastrado
else{
                    JOptionPane.showMessageDialog(null,"Este caixa já foi cadastrado!!");
                }
            }
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        q.setText("");
        f.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        TelaCadCaixa cad = this;
        SelecionaFuncionario sel = new SelecionaFuncionario();
        sel.setVisible(true);
        sel.setRp(cad);

        //               sel.setRp(cad);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar este caixa ?");
        if (resposta == JOptionPane.YES_OPTION) {
            Caixa p = new Caixa();
            Comcaixa dao;
            p.setDinheiro(Double.parseDouble((q.getText())));
            p.setIdfuncionario(Integer.parseInt((f.getText())));
            p.setId((int) tabela.getValueAt(tabela.getSelectedRow(), 0));  //pegamos o id da linha selecionada
            try {
                dao = new Comcaixa();
                dao.altera(p);
                readJTable();
            } catch (SQLException ex) {
                Logger.getLogger(TelaCadCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
            q.setText("");
            f.setText("");
          

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (tabela.getSelectedRow() != -1) {
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente apagar este caixa?");
            if (resposta == JOptionPane.YES_OPTION) {   //if para confirmacao

                Caixa p = new Caixa();
                p.setId((int) tabela.getValueAt(tabela.getSelectedRow(), 0));  //botando para dentro do array o valor do id
                Comcaixa dao;
                try {
                    dao = new Comcaixa();
                    dao.remove(p);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaCadCaixa.class.getName()).log(Level.SEVERE, null, ex);
                }

                q.setText("");
                f.setText("");
                try {
                    readJTable();  //para ler novamente para atualizar
                } catch (SQLException ex) {
                    Logger.getLogger(Comcaixa.class.getName()).log(Level.SEVERE, null, ex);
                }

            }} else {
                JOptionPane.showMessageDialog(null, "Selecione um caixa para excluir");
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    if (tabela.getSelectedRow() != -1) {   
           
           
            q.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        try {
            Comcaixa comcaixa = new Comcaixa();
             for (Caixa p : comcaixa.inter((int) tabela.getValueAt(tabela.getSelectedRow(), 0))) {
             f.setText(String.valueOf(p.getIdfuncionario()));
             }
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        }       
    }//GEN-LAST:event_tabelaMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
          this.setVisible(false);
    dispose();
    getTela().setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField q;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
